# Generated by Django 3.2.8 on 2021-10-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_first_name', models.CharField(blank=True, max_length=16, null=True)),
                ('default_last_name', models.CharField(blank=True, max_length=16, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_contact_number', models.CharField(blank=True, max_length=16, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
